apiVersion: v2
name: echo-headers
description: A Helm chart for deploying echo-headers in Kubernetes
type: application
version: 0.1.2
appVersion: "v1.0.0"
sources:
  - https://github.com/abhinav1107/echo-headers
