apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-headers.fullname" . }}
  labels:
    {{- include "echo-headers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "echo-headers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "echo-headers.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "echo-headers.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-port", "{{ .Values.service.port }}"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.healthCheck.enabled }}
          startupProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: {{ .Values.healthCheck.path }}
            initialDelaySeconds: {{ .Values.healthCheck.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthCheck.checkTimeOut }}
            periodSeconds: {{ .Values.healthCheck.startup.periodSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.startup.failureThreshold }}
          livenessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: {{ .Values.healthCheck.path }}
            initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthCheck.checkTimeOut }}
            periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: {{ .Values.healthCheck.path }}
            initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthCheck.checkTimeOut }}
            periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
            failureThreshold: {{ .Values.healthCheck.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
